### ISSUE TITLE
code to generate figures in notebooks file

### ISSUE THREAD

**Issue by Heng14** [google/hypernerf#18]
Hi Keunhong,

This is really nice work and I am wondering if you have tested the code to generate figures in the notebooks file (like hypernerf_ap_ds_figure.ipynb). I run this code and seems cannot work. Could you give some hints on how to use these code in  the notebooks file?
Thank you so much!

**Comment by keunhong** [comment]
Hi Heng,

Those are mostly there for posterity and unfortunately they won't run out of the box. The best way to get them running is probably to make a fresh notebook and copy each cell sequentially while making sure you understand each line.

Thanks,
Keunhong

**Comment by Heng14** [comment]
Hi Keunhong,

Thank you so much for your reply! I think I have run one of them successfully and I will keep looking into others.
Thank you again!
