### ISSUE TITLE
Inconsistent shapes between value and initializer for parameter "kernel" in "/warp_field/trunk/hidden_0"

### ISSUE THREAD

**Issue by mah-asd** [google/hypernerf#28]
in running eval.py with "hypernerf_vrig_ap_2d.gin" configuration I got this error: 

raise errors.ScopeParamShapeError(name, self.path_text, 
flax.errors.ScopeParamShapeError: Inconsistent shapes between value and initializer for parameter "kernel" in "/warp_field/trunk/hidden_0": (32, 128), (47, 128). (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.ScopeParamShapeError)

anyone has any idea?

**Comment by dengdengan** [comment]
Dear mah-asd
 Have you solved this problem? how？
