### ISSUE TITLE
Questions about camera coordinate and poses

### ISSUE THREAD

**Issue by dogyoonlee** [google/hypernerf#3]
I really appreciate to your awesome work!!

I have some questions about the camera pose matrix in `camera` folder's json files.

I'm reimplementing your paper on pytorch based nerf code.

However, I have confused about camera coordinate in `nerfies dataset`.

1. In `load_llff.py` in nerf pytorch code, they load the camera poses from `given poses_bounds.npy file` and correct their correct rotation matrix like follow codes.(poses matrix format is (3,  5, frame_num)

![image](https://user-images.githubusercontent.com/62277785/142342730-788002f1-86fa-4ac3-b716-eae6b0504678.png)

However, I could not find any correction part on your code when you generate the poses of dataset after loading them from given camera information json files.

I guess you used different coordinate system compared to original nerf(using llff dataset)

Then if I want to use your dataset as llff format and ray function, should I correct poses matrix like above code?

If you don't mind, could you explain the camera coordinate axis format of `COLMAP results`, `NeRF(llff)`, and `Nerfies(HyperNerf)`??

2. for dynamic scene dataset(called nvidia-dataset), there is no undistortion part for camera pose like follow part of your code.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/62277785/142343407-d514715a-75c6-4ea5-a7db-d81f933d384a.png">

I wonder the necessity of above part because nerfies dataset images seems to not be distorted.
and the dynamic scene dataset is pre-undistorted image? 

3. Did you implement your code on NDC coordinate?? 
 I wonder should I use the ndc_rays

I really hope your answer and appreciate to your great work again!!

Thank you.

**Comment by keunhong** [comment]
Answered in https://github.com/google/nerfies/issues/39.

Thanks!
