### ISSUE TITLE
Some tips on collecting selfie video for hypernerf?

### ISSUE THREAD

**Issue by deepshwang** [google/hypernerf#31]
Hi, Keunhong!

I was wondering if you could provide some rules-of-thumb on how to collect good selfie video so that hypernerf can converge to its best global optima. (My first trial wasn't so much successful despite calibrating my camera extrinsics using background only w/ COLMAP)

Any tips from others successfully trained their own selfie videos are welcomed to comment!

**Comment by deepshwang** [comment]
btw mine's performing well on train/val but not so much on test frames

**Comment by deepshwang** [comment]
realized that I should've adjusted the near-far bounds because my image descriptors are only from the backgrounds. closing the issue!

**Comment by ZXisSpider** [comment]
> realized that I should've adjusted the near-far bounds because my image descriptors are only from the backgrounds. closing the issue!

Hey, have you succeeded in reproducing the selfie experiment? I can't seem to reproduce that experiment, the result seems blurry and full of artifacts? Does adjusting near, far bound work for you?

**Comment by Zvyozdo4ka** [comment]
My first test is not promising, I still need any hint how to improve the output. It looks like i have two faces.

https://github.com/google/hypernerf/assets/74532816/ea44ec82-6018-4df9-beca-36efccc8e820

**Comment by ZXisSpider** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
